name: Sign package with Sigstore and release it to PyPI

on:
  release:
    types:
      - published

jobs:
  sign-and-release:
    permissions:
        id-token: write
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Compute checksums file for all files in the project
        run: | 
          find -type f -exec sha256sum "{}" + >| checksums.txt

      - name: Sign project with sigstore-python
        uses: sigstore/gh-action-sigstore-python@v1.1.0
        id: sigstore-python
        with:
          inputs: checksums.txt

      - name: Add and commit checksums file and Sigstore verification materials
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: "['checksums.txt', 'checksums.txt.sig', 'checksums.txt.crt', 'checksums.txt.sigstore']"
          author_name: Maya Costantini
          author_email: mcostant@redhat.com
          message: 'Update checksums.txt manifest'
          push: true
      
      - name: Install pypa/build
        run: |
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: |
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Publish 📦 the new project version to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
